# Use the official Streamlit base image
FROM streamlit/base

# Install wkhtmltopdf
RUN apt-get update && apt-get install -y wkhtmltopdf

# Install the required Python libraries
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Copy the Streamlit app code into the container
COPY . /app

# Set the working directory
WORKDIR /app

# Expose the port that Streamlit runs on
EXPOSE 8501

# Command to start the Streamlit app
CMD ["streamlit", "run", "app.py"]
